name: benchmark

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "14 04 * * *"


permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - run: npm ci --registry=https://registry.npmmirror.com
      - run: npm i --no-save express @sap/cds --registry=https://registry.npmmirror.com
      - run: npx tsc

      - name: Run benchmark
        run: node bench/benchmark.js | tee bench_output.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: cds-mysql benchmark
          tool: 'benchmarkjs'
          output-file-path: bench_output.txt
          github-token: ${{ secrets.BENCHMARK_ACTION_BOT_TOKEN }}
          alert-threshold: '200%'
          auto-push: ${{ github.event_name != 'pull_request' }}
          comment-always: true
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@Soontao'
          gh-repository: 'github.com/Soontao/cds-mysql-bench-result'