name: Benchmark.js

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "14 04 * * *"


permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run JavaScript Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - run: npm ci
      - run: npm run build

      - name: Run benchmark
        run: node bench/benchmark.js | tee bench_output.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Benchmark.js Benchmark
          tool: 'benchmarkjs'
          output-file-path: bench_output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alert-threshold: '200%'
          comment-always: true
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@Soontao'

