name: benchmark

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "14 04 * * *"


permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - run: npm i
      - run: npm i --no-save express @sap/cds
      - run: npx tsc

      - name: benchmark
        run: node bench/benchmark.js | tee bench_output.txt
        
      - name: cache benchmark data
        uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: 'cds-mysql benchmark'
          tool: 'benchmarkjs'
          output-file-path: bench_output.txt
          # GitHub API token to make a commit comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alert-threshold: '300%'
          # while PR, do not update benchmark data in cache
          save-data-file: ${{ github.event_name != 'pull_request' }}
          comment-always: true
          fail-on-alert: true
          alert-comment-cc-users: '@Soontao'
          external-data-json-path: ./cache/benchmark-data.json