name: benchmark

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "14 04 * * *"


permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - run: npm ci --registry=https://registry.npmmirror.com
      - run: npm i --no-save express @sap/cds --registry=https://registry.npmmirror.com
      - run: npx tsc

      - name: benchmark
        run: node bench/benchmark.js | tee bench_output.txt
        
      - name: cache benchmark data
        uses: actions/cache@v3
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: cds-mysql benchmark
          tool: 'benchmarkjs'
          output-file-path: bench_output.txt
          alert-threshold: '200%'
          comment-always: true
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@Soontao'
          external-data-json-path: ./cache/benchmark-data.json