name: database-test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  database-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        docker-images:
          [
            "mysql:5.6",
            "mysql:5.7",
            "mysql:8.0",
            "mariadb:10.5",
            "mariadb:10.8",
          ]

    services:
      db:
        image: ${{ matrix.docker-images }}
        env:
          MYSQL_DATABASE: cdstest
          MYSQL_USER: cdstest
          MYSQL_PASSWORD: cdstest
          MYSQL_ROOT_PASSWORD: cdstest
          MARIADB_DATABASE: cdstest
          MARIADB_USER: cdstest
          MARIADB_PASSWORD: cdstest
          MARIADB_ROOT_PASSWORD: cdstest
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=30s --health-timeout=5s --health-retries=10

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: install dependency
        run: |
          npm i -g npm
          npm install

      - name: test
        run: npm run test
        env:
          CI: true
          CDS_REQUIRES_MYSQL_CREDENTIALS_HOST: "127.0.0.1"
          CDS_REQUIRES_MYSQL_CREDENTIALS_PORT: ${{ job.services.db.ports[3306] }}
          CDS_REQUIRES_MYSQL_CREDENTIALS_DATABASE: cdstest
          CDS_REQUIRES_MYSQL_CREDENTIALS_USER: cdstest
          CDS_REQUIRES_MYSQL_CREDENTIALS_PASSWORD: cdstest
