name: mysql-test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  # daily check at 01:00 AM
  schedule:
    - cron: "0 1 * * *"

jobs:
  mysql:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mysql-version: ["mysql:5.6", "mysql:5.7", "mysql:8.0"]

    services:
      mysql:
        image: ${{ matrix.mysql-version }}
        env:
          MYSQL_DATABASE: cdstest
          MYSQL_USER: cdstest
          MYSQL_PASSWORD: cdstest
          MYSQL_ROOT_PASSWORD: cdstest
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=30s --health-timeout=5s --health-retries=10

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: install dependency
        run: |
          npm i -g npm
          npm install
          
      - name: coverage
        run: npm run coverage
        env:
          CI: true
          CDS_MYSQL_HOST: "127.0.0.1"
          CDS_MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
          CDS_MYSQL_DATABASE: cdstest
          CDS_MYSQL_USER: cdstest
          CDS_MYSQL_PASSWORD: cdstest
