name: node-ts-next-test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  # daily check at UTC 01:00 AM
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: npm install, build, and test
        run: |
          npm install
          npm install typescript@next
          npm run build --if-present
          npm run test
        env:
          CI: true
