name: node-test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  # daily check at 01:00 AM
  schedule:
    - cron: "32 11 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:10.8
        env:
          MYSQL_DATABASE: cdstest
          MYSQL_USER: cdstest
          MYSQL_PASSWORD: cdstest
          MYSQL_ROOT_PASSWORD: cdstest
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=30s --health-timeout=5s --health-retries=10

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - run: npm i -g npm

      - run: npm ci

      - name: test
        run: npm run test
        env:
          CI: true
          CDS_REQUIRES_MYSQL_CREDENTIALS_HOST: "127.0.0.1"
          CDS_REQUIRES_MYSQL_CREDENTIALS_PORT: ${{ job.services.mysql.ports[3306] }}
          CDS_REQUIRES_MYSQL_CREDENTIALS_DATABASE: cdstest
          CDS_REQUIRES_MYSQL_CREDENTIALS_USER: cdstest
          CDS_REQUIRES_MYSQL_CREDENTIALS_PASSWORD: cdstest

