name: node-release

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:10.4
        env:
          MYSQL_DATABASE: cds_test
          MYSQL_USER: cds_test
          MYSQL_PASSWORD: cds_test
          MYSQL_ROOT_PASSWORD: cds_test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=30s --health-timeout=5s --health-retries=10

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/

      - name: npm test
        run: |
          npm install
          npm test
        env:
          CI: true
          MYSQL_HOST: "127.0.0.1"
          MYSQL_PORT: "3306"

      - name: npm auth & publish
        run: npm run build && npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.Z_NPM_TOKEN}}
