name: node-test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "32 11 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:12
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=30s --health-timeout=5s --health-retries=10

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm i -g npm

      - run: npm i

      - name: setup mysql user
        run: node ./docker/create_user.js

      - name: test
        run: npm run test
        env:
          CI: true
          CDS_REQUIRES_DB_CREDENTIALS_HOST: "127.0.0.1"
          CDS_REQUIRES_DB_CREDENTIALS_PORT: 3306
          CDS_REQUIRES_DB_CREDENTIALS_DATABASE: cds_admin
          CDS_REQUIRES_DB_CREDENTIALS_USER: cds_admin
          CDS_REQUIRES_DB_CREDENTIALS_PASSWORD: cds_admin
