name: stage-runtime-test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  # daily check at UTC 01:00 AM
  schedule:
    - cron: "0 2 * * *"

jobs:
  ts-next-build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:10.4
        env:
          MYSQL_DATABASE: cdstest
          MYSQL_USER: cdstest
          MYSQL_PASSWORD: cdstest
          MYSQL_ROOT_PASSWORD: cdstest
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=30s --health-timeout=5s --health-retries=10

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: npm install, build, and test
        run: |
          npm install
          npm install typescript@next
          npm run build --if-present
          npm run test
        env:
          CI: true
          MYSQL_HOST: "127.0.0.1"
          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
          MYSQL_DATABASE: cdstest
          MYSQL_USER: cdstest
          MYSQL_PASSWORD: cdstest

  mysql-next-build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: cdstest
          MYSQL_USER: cdstest
          MYSQL_PASSWORD: cdstest
          MYSQL_ROOT_PASSWORD: cdstest
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=30s --health-timeout=5s --health-retries=10

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test
        env:
          CI: true
          MYSQL_HOST: "127.0.0.1"
          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
          MYSQL_DATABASE: cdstest
          MYSQL_USER: cdstest
          MYSQL_PASSWORD: cdstest
