name: node-release

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/

      - name: npm test
        run: |
          npm install
          npm test
        env:
          CI: true

      - name: npm auth & publish
        run: npm run build && npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.Z_NPM_TOKEN}}
