name: node-release

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:10
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=30s --health-timeout=5s --health-retries=10

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/

      - run: npm i -g npm
      
      - run: npm i

      - name: setup mysql user
        run: node ./docker/create_user.js

      - name: npm test
        run: npm test
        env:
          CI: true
          CDS_REQUIRES_DB_CREDENTIALS_HOST: "127.0.0.1"
          CDS_REQUIRES_DB_CREDENTIALS_PORT: 3306
          CDS_REQUIRES_DB_CREDENTIALS_DATABASE: cds_admin
          CDS_REQUIRES_DB_CREDENTIALS_USER: cds_admin
          CDS_REQUIRES_DB_CREDENTIALS_PASSWORD: cds_admin

      - run: rm -rf node_modules

      - run: node overwrite_package_json.js

      - run: npm shrinkwrap

      - name: npm auth & publish
        run: npm run build && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.Z_NPM_TOKEN}}
