name: tidb-test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  tidb:
    runs-on: ubuntu-latest
    services:
      db:
        image: thedockerimages/tidb:latest
        ports:
          - 4000:4000
        options: --health-cmd="mysqladmin ping --host 127.0.0.1 --port 4000 -u root" --health-interval=30s --health-timeout=5s --health-retries=10

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: setup tidb user
        run: docker exec -it db --host 127.0.0.1 --port 4000 -u root < docker/tidb/create_user.sql
        
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: npm install, build
        run: |
          npm i -g npm
          npm install
          npm run build --if-present

      - name: test
        run: npm run test
        env:
          CI: true
          CDS_REQUIRES_MYSQL_CREDENTIALS_HOST: ${{ secrets.TIDB_CLOUD_HOST }}
          CDS_REQUIRES_MYSQL_CREDENTIALS_PORT: 4000
          CDS_REQUIRES_MYSQL_CREDENTIALS_DATABASE: cdstest
          CDS_REQUIRES_MYSQL_CREDENTIALS_USER: cdstest
          CDS_REQUIRES_MYSQL_CREDENTIALS_PASSWORD: cdstest
